### ISSUE TITLE
Does nothing

### ISSUE THREAD

**Issue by signothefish** [AtomLinter/linter-slim#7] opened 2015-09-21 20:45 UTC
This doesn't do any linting on my Slim files.  I have the path set to Executable Dir: C:/Ruby22-x64/bin and the binary set to Binary Name: slim-lint.  This executes in a Ruby command shell fine, and catches issues with my Slim code, printing them out on STDOUT, but inside Atom it doesn't appear to do anything, since nothing is printed at the bottom showing what the problems are after saving my file.

**Comment by lloeki** [comment] 2015-09-21 20:47
This plugin needs an update to comply with the new linter API.

**Comment by maletor** [comment] 2015-09-28 16:47
Duplicate of #5.

**Closed by maletor** 2015-09-28 16:47 UTC
